/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    City: typeof import('./components/tile/backgrounds/city.vue')['default']
    Corner: typeof import('./components/corner/index.vue')['default']
    Edge: typeof import('./components/edge/index.vue')['default']
    Forest: typeof import('./components/tile/backgrounds/forest.vue')['default']
    Grassland: typeof import('./components/tile/backgrounds/grassland.vue')['default']
    House: typeof import('./components/corner/house.vue')['default']
    Layout: typeof import('./components/layout.vue')['default']
    Marker: typeof import('./components/corner/marker/index.vue')['default']
    Mountain: typeof import('./components/tile/backgrounds/mountain.vue')['default']
    Number: typeof import('./components/tile/number.vue')['default']
    Ocean: typeof import('./components/tile/backgrounds/ocean.vue')['default']
    Resource: typeof import('./components/sidebar/main/resource.vue')['default']
    Sidebar: typeof import('./components/sidebar/index.vue')['default']
    SidebarButtons: typeof import('./components/sidebar/sidebarButtons.vue')['default']
    SidebarInfo: typeof import('./components/sidebar/sidebarInfo.vue')['default']
    SidebarMain: typeof import('./components/sidebar/sidebarMain.vue')['default']
    SidebarMessage: typeof import('./components/sidebar/sidebarMessage.vue')['default']
    Stone: typeof import('./components/tile/backgrounds/stone.vue')['default']
    Tile: typeof import('./components/tile/index.vue')['default']
    Wheat: typeof import('./components/tile/backgrounds/wheat.vue')['default']
    WorldMap: typeof import('./components/worldMap.vue')['default']
  }
}
